### ISSUE TITLE
Command-line interface

### ISSUE THREAD

**Issue by sandio** [WeAreAthlon/silla.io#15]
Create a command-line interface:
- [ ] Migrations CLI command #14
- [x] Update entity CLI command #16 
- [x] Rename entity CLI command #17 
- [x] Clear entity CLI command #18
- [ ] Generate CLI command #19
- [ ] Create database CLI command #20
- [x] Rename property CLI command #21 
- [ ] Generate SQL from datasources CLI command #22
