### ISSUE TITLE
New database layer

### ISSUE THREAD

**Issue by sandio** [WeAreAthlon/silla.io#5]
Build a stable and clean database layer.
- [ ] Database cache #4 
- [ ] Create basic database objects #6 
- [ ] Create basic database property types #7 
- [ ] Remove the base model and us database Object Record instead #8
- [ ] Create strategy for implementing behaviours #9
- [ ] Create a database Filter object #10
- [ ] Create a database Query object #11
- [ ] Add support for transactions #12
- [ ] Implement cache strategy for queries #13
